name: Discord Notification on Push

on:
  push:

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          BRANCH: ${{ github.ref_name }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_TIME: ${{ github.event.head_commit.timestamp }}
        run: |
          echo "Preparing Discord payload..."
          # Extract the first line from the commit message to use as the push title.
          COMMIT_TITLE=$(echo "$COMMIT_MESSAGE" | head -n 1)

          # Convert COMMIT_TIME (which is in ISO UTC format) to EST (America/New_York)
          # and format it as MM/DD/YYYY, HH:MM:SS AM/PM.
          FORMATTED_TIME=$(TZ="America/New_York" date -d "$COMMIT_TIME" "+%m/%d/%Y, %I:%M:%S %p")

          # Use jq to safely construct a valid JSON payload.
          payload=$(jq -n \
            --arg username "GitHub Bot" \
            --arg title "$COMMIT_TITLE" \
            --arg message "$COMMIT_MESSAGE" \
            --arg branch "$BRANCH" \
            --arg time "$FORMATTED_TIME" \
            '{
              username: $username,
              embeds: [{
                title: ("Push Notification: " + $title),
                description: ("**Commit Message:** " + $message + "\n**Branch:** " + $branch + "\n**Time (EST):** " + $time),
                color: 3447003
              }]
            }'
          )

          echo "Sending Discord notification..."
          curl -H "Content-Type: application/json" \
               -X POST \
               -d "$payload" \
               "$DISCORD_WEBHOOK_URL"
